name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Single Cell RNA data analysis"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: fehmeedamustafa/single_cell_rna
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
          tag: latest
