name: Single Cell RNA data analysis

on:
  workflow_dispatch:
  
jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest

    steps:          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R packages and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libxml2-dev # Install system dependencies
          R -e "install.packages(c('usethis', 'pkgdown', 'rcmdcheck', 'roxygen2', 'rversions', 'urlchecker'), repos='https://cloud.r-project.org/')"
          R -e "install.packages('devtools', repos='https://cloud.r-project.org/')"
          R -e "devtools::install_github('immunogenomics/presto')"
        
      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::Seurat
            any::ggplot2
            any::tidyverse
            any::gridExtra
            any::SeuratObject
            any::patchwork
            any::celldex
            any::openxlsx
            any::SingleR
            any::pheatmap
            any::org.Hs.eg.db
            any::hdf5r
            any::readxl
            any::viridis

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts 
        run: |  
          Rscript GSE233615-SingleCellRNAseq-script2.R
          Rscript updated_single-cell-analysis-R-script.R
