name: Single Cell RNA data analysis

on: [push]
  
jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::Seurat
            any::ggplot2
            any::tidyverse
            any::gridExtra
            any::SeuratObject
            any::patchwork
            any::celldex
            any::openxlsx
            any::SingleR
            any::pheatmap
            any::org.Hs.eg.db
            any::hdf5r
            any::readxl
            any::viridis
     
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts 
        run: |  
          Rscript GSE233615-SingleCellRNAseq-script2.R

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: samreenraza40/microarray_data_analysis_scripts
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
